class BackSpaceStringCompare {
    public boolean backspaceCompare(String S, String T) {
        
        // Find the string after processing both S and T and compare them
        return processString(S).equals(processString(T));
    }
    
    public String processString(String S){
        
        //Initialize a stack
        Stack<Character> s = new Stack<>();
        
        //Traverse through the String one character at a time
        for(char ch: S.toCharArray()){
            
            //if character is equal to #, then pop an element if stack is not empty
            if(ch == '#'){
                if(!s.isEmpty())
                    s.pop();
            }
            
            // else push character to stack
            else
                s.push(ch);
        }
        
        //return the string generated by stack
        return s.toString();
    }
}
